image : docker
variables:
  DOCKER_DRIVER: overlay2

stages :
  - build
 
build:
  stage : build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE . 
    - docker push $CI_REGISTRY_IMAGE
