before_script:
  - apt-get install curl
build :
  - "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/remche/docker-ttk/trigger/f02c71b4-5582-4e95-92b0-f43a73dd7d50/"