FROM quay.io/pypa/manylinux2010_x86_64

ENV CMAKE_VERSION 3.14.4
ENV SWIG_VERSION 4.0.0
ENV CGAL_VERSION 4.13.1
ENV BOOST_VERSION 1_70_0
ENV BOOST_INCLUDEDIR /usr/local/include/boost
ENV OMPI_MAJOR_VERSION 3.1
ENV OMPI_MINOR_VERSION 3.1.4


RUN yum -y install \
      eigen3-devel \
      gmp-devel \
      mpfr-devel \
      pcre-devel \
      qt5-qtbase-devel \
      qt5-qtsvg-devel \
      R \
      readline \
      zlib-devel


# CMAKE
WORKDIR /tmp/build
RUN curl -L  https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.tar.gz -o cmake-$CMAKE_VERSION.tar.gz && \
      tar xvzf cmake-$CMAKE_VERSION.tar.gz

WORKDIR /tmp/build/cmake-$CMAKE_VERSION
RUN ./bootstrap && \
      make && \
      make install

# SWIG
WORKDIR /tmp/build
RUN curl -L https://sourceforge.net/projects/swig/files/swig/swig-$SWIG_VERSION/swig-$SWIG_VERSION.tar.gz -o swig-$SWIG_VERSION.tar.gz && \
      tar xvzf swig-$SWIG_VERSION.tar.gz

WORKDIR /tmp/build/swig-$SWIG_VERSION
RUN ./configure && \
      make && \
      make install

# BOOST
WORKDIR /tmp/build
RUN curl https://dl.bintray.com/boostorg/release/1.70.0/source/boost_$BOOST_VERSION.tar.gz -o boost_$BOOST_VERSION.tar.gz && \
      tar xvzf boost_$BOOST_VERSION.tar.gz

WORKDIR /tmp/build/boost_$BOOST_VERSION
RUN ./bootstrap.sh && \
      ./b2 install


# CGAL
WORKDIR /tmp/build
RUN curl -L  https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-$CGAL_VERSION/CGAL-$CGAL_VERSION.zip -o cgal-$CGAL_VERSION.zip && \
      unzip  cgal-$CGAL_VERSION.zip

WORKDIR /tmp/build/CGAL-$CGAL_VERSION
RUN cmake . -DCMAKE_BUILD_TYPE="Release" && \
      make && \
      make install

# OPENMPI
WORKDIR /tmp/build
RUN curl -L https://download.open-mpi.org/release/open-mpi/v$OMPI_MAJOR_VERSION/openmpi-$OMPI_MINOR_VERSION.tar.gz -o openmpi-MINOR_VERSIO.tar.gz && \
      tar xvzf openmpi-$OMPI_MINOR_VERSION.tar.gz

WORKDIR /tmp/build/openmpi-$OMPI_MINOR_VERSION
RUN ./configure && \
      make all install


RUN rm -rf /tmp/build
